name: ebfitness-frontend

services:
  web:
    build:
      context: .
      args:
        VITE_API_BASE_URL: https://www.ebfitness.co/api
        VITE_API_IMAGE_URL: https://www.ebfitness.co
    ports: !override
      - "127.0.0.1:5173:80"
